# -*- coding: utf-8 -*-
"""heat_maps_PRUEBA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ddgoWUmwhfxy1vSesAtCPUEFyn-Hgvv
"""

from google.colab import drive
drive.mount('/content/drive')

import cv2
import numpy as np
img = cv2.imread('/273278,9eedb000c088122e.jpg')
lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
a_component = lab[:,:,1]
th = cv2.threshold(a_component,140,255,cv2.THRESH_BINARY)[1]
blur = cv2.GaussianBlur(th,(13,13), 11)
heatmap_img = cv2.applyColorMap(blur, cv2.COLORMAP_JET)
super_imposed_img = cv2.addWeighted(heatmap_img, 1, img, 2, 0)
cv2_imshow(img)
cv2_imshow(heatmap_img)

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
#import cv2_imshow

def process(img):
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img_th = cv2.threshold(img_gray,140,255,cv2.THRESH_BINARY)[1]

    img_blur = cv2.GaussianBlur(img_th, (15, 15), 25)
    img_canny = cv2.Canny(img_blur, 1, 0.5)
    kernel = np.ones((3, 3))
    img_dilate = cv2.dilate(img_canny, kernel, iterations=1) #4
    img_erode = cv2.erode(img_dilate, kernel, iterations=1)
    return img_erode

def get_contours(img, img_original):
    img_contours = img_original.copy()
    contours, hierarchies = cv2.findContours(img, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)

    cv2.drawContours(img_contours, contours, -1, (0, 255, 0), -1) 
    # If you want to omit smaller contours, loop through the detected contours, and only draw them on the image if they are at least a specific area. Don't forget to remove the line above if you choose the below block of code.
    # for cnt in contours: 
    #     if cv2.contourArea(cnt) > 500:
    #         cv2.drawContours(img_contours, [cnt], -1, (0, 255, 0), -1) 

    return img_contours

cap = cv2.VideoCapture("gente.mp4")

success, img1 = cap.read()
success, img2 = cap.read()
heat_map = np.zeros(img1.shape[:-1])

while success:
    diff = cv2.absdiff(img1, img2)
    img_contours = get_contours(process(diff), img1)

    heat_map[np.all(img_contours == [0, 255, 0], 2)] += 3 # The 3 can be tweaked depending on how fast you want the colors to respond
    heat_map[np.any(img_contours != [0, 255, 0], 2)] -= 3
    heat_map[heat_map < 0] = 0
    heat_map[heat_map > 255] = 255

    img_mapped = cv2.applyColorMap(heat_map.astype('uint8'), cv2.COLORMAP_JET)

#    img1[heat_map > 160] = img_mapped[heat_map > 160] Use this line to draw the heat map on the original video at a specific temperature range. For this it's where ever the temperature is above 160 (min is 0 and max is 255)

    cv2_imshow(img1)
    cv2_imshow(img_mapped)
    
    img1 = img2
    success, img2 = cap.read()
        
    if cv2.waitKey(1) == ord('q'):
        break